# Generated by Django 4.2.4 on 2023-08-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("christmas", "0002_user_wish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wish",
            options={"verbose_name_plural": "Wishes"},
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="christmas.group",
            ),
        ),
    ]
