# Generated by Django 4.2.4 on 2023-08-17 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("christmas", "0003_alter_wish_options_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
