# Generated by Django 4.2.4 on 2023-08-17 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("christmas", "0004_user_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="identifier",
            field=models.UUIDField(
                default=uuid.UUID("c4ac354c-f3a0-419f-ad27-81f0bf915d8d"),
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="wish",
            name="identifier",
            field=models.UUIDField(
                default=uuid.UUID("c4a7c3ce-b8bc-4af9-a4f5-82907d77bcde"),
                editable=False,
            ),
        ),
    ]
