# Generated by Django 4.2.4 on 2023-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("christmas", "0007_comment_created_at_wish_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="contributors",
            field=models.ManyToManyField(to="christmas.user"),
        ),
    ]
