# Generated by Django 4.2.4 on 2023-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("christmas", "0008_wish_contributors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="wish",
            options={"ordering": ["created_at"], "verbose_name_plural": "Wishes"},
        ),
        migrations.AddField(
            model_name="wish",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
